import { Router } from "express";

type OpenApiRouteRegistration = {
  method: "get" | "post" | "patch" | "put" | "delete";
  path: string;
  summary?: string;
  tags?: string[];
};

// Path inventory generated from doc/plans/2026-05-23-cli-api-parity-openapi-reference.ts.
// Keep this lightweight route in sync when the reference snapshot or mounted API surface changes.
const OPENAPI_ROUTE_REGISTRATIONS: OpenApiRouteRegistration[] = [
  {"method":"get","path":"/api/health","summary":"Health check","tags":["health"]},
  {"method":"get","path":"/api/openapi.json","summary":"Get the generated OpenAPI document","tags":["health"]},
  {"method":"get","path":"/api/companies","summary":"List companies","tags":["companies"]},
  {"method":"post","path":"/api/companies","summary":"Create a company","tags":["companies"]},
  {"method":"get","path":"/api/companies/stats","summary":"Company stats","tags":["companies"]},
  {"method":"get","path":"/api/companies/{companyId}","summary":"Get a company","tags":["companies"]},
  {"method":"patch","path":"/api/companies/{companyId}","summary":"Update a company","tags":["companies"]},
  {"method":"patch","path":"/api/companies/{companyId}/branding","summary":"Update company branding","tags":["companies"]},
  {"method":"post","path":"/api/companies/{companyId}/archive","summary":"Archive a company","tags":["companies"]},
  {"method":"delete","path":"/api/companies/{companyId}","summary":"Delete a company","tags":["companies"]},
  {"method":"get","path":"/api/companies/{companyId}/feedback-traces","summary":"List company feedback traces","tags":["companies"]},
  {"method":"post","path":"/api/companies/{companyId}/exports","summary":"Export company data","tags":["companies"]},
  {"method":"post","path":"/api/companies/{companyId}/exports/preview","summary":"Preview company export","tags":["companies"]},
  {"method":"post","path":"/api/companies/{companyId}/imports/preview","summary":"Preview company import","tags":["companies"]},
  {"method":"post","path":"/api/companies/{companyId}/imports/apply","summary":"Apply company import","tags":["companies"]},
  {"method":"get","path":"/api/companies/{companyId}/agents","summary":"List agents in a company","tags":["agents"]},
  {"method":"post","path":"/api/companies/{companyId}/agents","summary":"Create an agent","tags":["agents"]},
  {"method":"post","path":"/api/companies/{companyId}/agent-hires","summary":"Hire an agent","tags":["agents"]},
  {"method":"get","path":"/api/companies/{companyId}/agent-configurations","summary":"List agent configurations for a company","tags":["agents"]},
  {"method":"get","path":"/api/companies/{companyId}/org","summary":"Get org chart data","tags":["agents"]},
  {"method":"get","path":"/api/agents/me","summary":"Get the current agent","tags":["agents"]},
  {"method":"get","path":"/api/agents/me/inbox-lite","summary":"Get current agent inbox (lite)","tags":["agents"]},
  {"method":"get","path":"/api/agents/me/inbox/mine","summary":"Get current agent assigned inbox items","tags":["agents"]},
  {"method":"get","path":"/api/agents/{id}","summary":"Get an agent","tags":["agents"]},
  {"method":"patch","path":"/api/agents/{id}","summary":"Update an agent","tags":["agents"]},
  {"method":"delete","path":"/api/agents/{id}","summary":"Delete an agent","tags":["agents"]},
  {"method":"patch","path":"/api/agents/{id}/permissions","summary":"Update agent permissions","tags":["agents"]},
  {"method":"patch","path":"/api/agents/{id}/instructions-path","summary":"Update agent instructions path","tags":["agents"]},
  {"method":"get","path":"/api/agents/{id}/instructions-bundle","summary":"Get agent instructions bundle","tags":["agents"]},
  {"method":"patch","path":"/api/agents/{id}/instructions-bundle","summary":"Update agent instructions bundle","tags":["agents"]},
  {"method":"get","path":"/api/agents/{id}/instructions-bundle/file","summary":"Get agent instructions file","tags":["agents"]},
  {"method":"put","path":"/api/agents/{id}/instructions-bundle/file","summary":"Upsert agent instructions file","tags":["agents"]},
  {"method":"delete","path":"/api/agents/{id}/instructions-bundle/file","summary":"Delete agent instructions file","tags":["agents"]},
  {"method":"get","path":"/api/agents/{id}/configuration","summary":"Get agent configuration","tags":["agents"]},
  {"method":"get","path":"/api/agents/{id}/config-revisions","summary":"List agent config revisions","tags":["agents"]},
  {"method":"get","path":"/api/agents/{id}/config-revisions/{revisionId}","summary":"Get an agent config revision","tags":["agents"]},
  {"method":"post","path":"/api/agents/{id}/config-revisions/{revisionId}/rollback","summary":"Roll back to a config revision","tags":["agents"]},
  {"method":"get","path":"/api/agents/{id}/runtime-state","summary":"Get agent runtime state","tags":["agents"]},
  {"method":"post","path":"/api/agents/{id}/runtime-state/reset-session","summary":"Reset agent session","tags":["agents"]},
  {"method":"get","path":"/api/agents/{id}/task-sessions","summary":"List agent task sessions","tags":["agents"]},
  {"method":"get","path":"/api/agents/{id}/skills","summary":"List agent skills","tags":["agents"]},
  {"method":"post","path":"/api/agents/{id}/skills/sync","summary":"Sync desired skills onto an agent configuration","tags":["agents"]},
  {"method":"get","path":"/api/agents/{id}/keys","summary":"List agent API keys","tags":["agents"]},
  {"method":"post","path":"/api/agents/{id}/keys","summary":"Create an agent API key","tags":["agents"]},
  {"method":"delete","path":"/api/agents/{id}/keys/{keyId}","summary":"Delete an agent API key","tags":["agents"]},
  {"method":"post","path":"/api/agents/{id}/wakeup","summary":"Wake up an agent","tags":["agents"]},
  {"method":"post","path":"/api/agents/{id}/pause","summary":"Pause an agent","tags":["agents"]},
  {"method":"post","path":"/api/agents/{id}/resume","summary":"Resume an agent","tags":["agents"]},
  {"method":"post","path":"/api/agents/{id}/terminate","summary":"Terminate an agent","tags":["agents"]},
  {"method":"get","path":"/api/instance/scheduler-heartbeats","summary":"List scheduler heartbeats","tags":["agents"]},
  {"method":"get","path":"/api/companies/{companyId}/adapters/{type}/models","summary":"List models for an adapter type","tags":["adapters"]},
  {"method":"get","path":"/api/companies/{companyId}/adapters/{type}/detect-model","summary":"Detect active model for an adapter","tags":["adapters"]},
  {"method":"post","path":"/api/companies/{companyId}/adapters/{type}/test-environment","summary":"Validate adapter environment access for a company","tags":["adapters"]},
  {"method":"get","path":"/api/companies/{companyId}/issues","summary":"List issues in a company","tags":["issues"]},
  {"method":"post","path":"/api/companies/{companyId}/issues","summary":"Create an issue","tags":["issues"]},
  {"method":"get","path":"/api/issues/{id}","summary":"Get an issue","tags":["issues"]},
  {"method":"patch","path":"/api/issues/{id}","summary":"Update an issue","tags":["issues"]},
  {"method":"delete","path":"/api/issues/{id}","summary":"Delete an issue","tags":["issues"]},
  {"method":"get","path":"/api/issues/{id}/heartbeat-context","summary":"Get issue heartbeat context","tags":["issues"]},
  {"method":"get","path":"/api/issues/{id}/work-products","summary":"List issue work products","tags":["issues"]},
  {"method":"post","path":"/api/issues/{id}/work-products","summary":"Create an issue work product","tags":["issues"]},
  {"method":"patch","path":"/api/work-products/{id}","summary":"Update a work product","tags":["issues"]},
  {"method":"delete","path":"/api/work-products/{id}","summary":"Delete a work product","tags":["issues"]},
  {"method":"get","path":"/api/issues/{id}/documents","summary":"List issue documents","tags":["issues"]},
  {"method":"get","path":"/api/issues/{id}/documents/{key}","summary":"Get an issue document","tags":["issues"]},
  {"method":"put","path":"/api/issues/{id}/documents/{key}","summary":"Upsert an issue document","tags":["issues"]},
  {"method":"delete","path":"/api/issues/{id}/documents/{key}","summary":"Delete an issue document","tags":["issues"]},
  {"method":"get","path":"/api/issues/{id}/documents/{key}/revisions","summary":"List issue document revisions","tags":["issues"]},
  {"method":"post","path":"/api/issues/{id}/documents/{key}/revisions/{revisionId}/restore","summary":"Restore a document revision","tags":["issues"]},
  {"method":"get","path":"/api/issues/{id}/comments","summary":"List issue comments","tags":["issues"]},
  {"method":"post","path":"/api/issues/{id}/comments","summary":"Add a comment to an issue","tags":["issues"]},
  {"method":"delete","path":"/api/issues/{id}/comments/{commentId}","summary":"Delete an issue comment","tags":["issues"]},
  {"method":"get","path":"/api/issues/{id}/approvals","summary":"List issue approvals","tags":["issues"]},
  {"method":"post","path":"/api/issues/{id}/approvals","summary":"Link an approval to an issue","tags":["issues"]},
  {"method":"delete","path":"/api/issues/{id}/approvals/{approvalId}","summary":"Unlink an approval from an issue","tags":["issues"]},
  {"method":"post","path":"/api/issues/{id}/checkout","summary":"Check out an issue","tags":["issues"]},
  {"method":"post","path":"/api/issues/{id}/release","summary":"Release an issue","tags":["issues"]},
  {"method":"post","path":"/api/issues/{id}/read","summary":"Mark an issue as read","tags":["issues"]},
  {"method":"delete","path":"/api/issues/{id}/read","summary":"Mark an issue as unread","tags":["issues"]},
  {"method":"post","path":"/api/issues/{id}/inbox-archive","summary":"Archive issue from inbox","tags":["issues"]},
  {"method":"delete","path":"/api/issues/{id}/inbox-archive","summary":"Un-archive issue from inbox","tags":["issues"]},
  {"method":"get","path":"/api/issues/{id}/feedback-votes","summary":"List issue feedback votes","tags":["issues"]},
  {"method":"post","path":"/api/issues/{id}/feedback-votes","summary":"Upsert a feedback vote","tags":["issues"]},
  {"method":"get","path":"/api/issues/{id}/feedback-traces","summary":"List issue feedback traces","tags":["issues"]},
  {"method":"get","path":"/api/feedback-traces/{traceId}","summary":"Get a feedback trace","tags":["issues"]},
  {"method":"get","path":"/api/feedback-traces/{traceId}/bundle","summary":"Get a feedback trace bundle","tags":["issues"]},
  {"method":"get","path":"/api/issues/{id}/attachments","summary":"List issue attachments","tags":["issues"]},
  {"method":"get","path":"/api/companies/{companyId}/labels","summary":"List labels in a company","tags":["issues"]},
  {"method":"post","path":"/api/companies/{companyId}/labels","summary":"Create a label","tags":["issues"]},
  {"method":"delete","path":"/api/labels/{labelId}","summary":"Delete a label","tags":["issues"]},
  {"method":"get","path":"/api/companies/{companyId}/projects","summary":"List projects in a company","tags":["projects"]},
  {"method":"post","path":"/api/companies/{companyId}/projects","summary":"Create a project","tags":["projects"]},
  {"method":"get","path":"/api/projects/{id}","summary":"Get a project","tags":["projects"]},
  {"method":"patch","path":"/api/projects/{id}","summary":"Update a project","tags":["projects"]},
  {"method":"delete","path":"/api/projects/{id}","summary":"Delete a project","tags":["projects"]},
  {"method":"get","path":"/api/projects/{id}/workspaces","summary":"List project workspaces","tags":["projects"]},
  {"method":"post","path":"/api/projects/{id}/workspaces","summary":"Create a project workspace","tags":["projects"]},
  {"method":"patch","path":"/api/projects/{id}/workspaces/{workspaceId}","summary":"Update a project workspace","tags":["projects"]},
  {"method":"delete","path":"/api/projects/{id}/workspaces/{workspaceId}","summary":"Delete a project workspace","tags":["projects"]},
  {"method":"get","path":"/api/companies/{companyId}/routines","summary":"List routines in a company","tags":["routines"]},
  {"method":"post","path":"/api/companies/{companyId}/routines","summary":"Create a routine","tags":["routines"]},
  {"method":"get","path":"/api/routines/{id}","summary":"Get a routine","tags":["routines"]},
  {"method":"patch","path":"/api/routines/{id}","summary":"Update a routine","tags":["routines"]},
  {"method":"get","path":"/api/routines/{id}/runs","summary":"List runs for a routine","tags":["routines"]},
  {"method":"post","path":"/api/routines/{id}/run","summary":"Manually run a routine","tags":["routines"]},
  {"method":"post","path":"/api/routines/{id}/triggers","summary":"Create a routine trigger","tags":["routines"]},
  {"method":"patch","path":"/api/routine-triggers/{id}","summary":"Update a routine trigger","tags":["routines"]},
  {"method":"delete","path":"/api/routine-triggers/{id}","summary":"Delete a routine trigger","tags":["routines"]},
  {"method":"post","path":"/api/routine-triggers/{id}/rotate-secret","summary":"Rotate a routine trigger secret","tags":["routines"]},
  {"method":"post","path":"/api/routine-triggers/public/{publicId}/fire","summary":"Fire a public routine trigger","tags":["routines"]},
  {"method":"get","path":"/api/companies/{companyId}/goals","summary":"List goals in a company","tags":["goals"]},
  {"method":"post","path":"/api/companies/{companyId}/goals","summary":"Create a goal","tags":["goals"]},
  {"method":"get","path":"/api/goals/{id}","summary":"Get a goal","tags":["goals"]},
  {"method":"patch","path":"/api/goals/{id}","summary":"Update a goal","tags":["goals"]},
  {"method":"delete","path":"/api/goals/{id}","summary":"Delete a goal","tags":["goals"]},
  {"method":"get","path":"/api/companies/{companyId}/secret-providers","summary":"List secret providers","tags":["secrets"]},
  {"method":"get","path":"/api/companies/{companyId}/secrets","summary":"List secrets in a company","tags":["secrets"]},
  {"method":"post","path":"/api/companies/{companyId}/secrets","summary":"Create a secret","tags":["secrets"]},
  {"method":"patch","path":"/api/secrets/{id}","summary":"Update a secret","tags":["secrets"]},
  {"method":"post","path":"/api/secrets/{id}/rotate","summary":"Rotate a secret","tags":["secrets"]},
  {"method":"delete","path":"/api/secrets/{id}","summary":"Delete a secret","tags":["secrets"]},
  {"method":"get","path":"/api/companies/{companyId}/approvals","summary":"List approvals in a company","tags":["approvals"]},
  {"method":"post","path":"/api/companies/{companyId}/approvals","summary":"Create an approval","tags":["approvals"]},
  {"method":"get","path":"/api/approvals/{id}","summary":"Get an approval","tags":["approvals"]},
  {"method":"get","path":"/api/approvals/{id}/issues","summary":"List issues linked to an approval","tags":["approvals"]},
  {"method":"post","path":"/api/approvals/{id}/approve","summary":"Approve an approval","tags":["approvals"]},
  {"method":"post","path":"/api/approvals/{id}/reject","summary":"Reject an approval","tags":["approvals"]},
  {"method":"post","path":"/api/approvals/{id}/request-revision","summary":"Request revision on an approval","tags":["approvals"]},
  {"method":"post","path":"/api/approvals/{id}/resubmit","summary":"Resubmit an approval","tags":["approvals"]},
  {"method":"get","path":"/api/approvals/{id}/comments","summary":"List approval comments","tags":["approvals"]},
  {"method":"post","path":"/api/approvals/{id}/comments","summary":"Add a comment to an approval","tags":["approvals"]},
  {"method":"get","path":"/api/companies/{companyId}/cost-events","summary":"Record a cost event","tags":["costs"]},
  {"method":"post","path":"/api/companies/{companyId}/finance-events","summary":"Record a finance event","tags":["costs"]},
  {"method":"post","path":"/api/companies/{companyId}/budgets/policies","summary":"Create or update a budget policy","tags":["costs"]},
  {"method":"post","path":"/api/companies/{companyId}/budget-incidents/{incidentId}/resolve","summary":"Resolve a budget incident","tags":["costs"]},
  {"method":"get","path":"/api/companies/{companyId}/budgets/overview","summary":"Get budget overview","tags":["costs"]},
  {"method":"patch","path":"/api/companies/{companyId}/budgets","summary":"Update company budget","tags":["costs"]},
  {"method":"patch","path":"/api/agents/{agentId}/budgets","summary":"Update agent budget","tags":["costs"]},
  {"method":"get","path":"/api/companies/{companyId}/activity","summary":"List company activity","tags":["activity"]},
  {"method":"post","path":"/api/companies/{companyId}/activity","summary":"Create an activity entry","tags":["activity"]},
  {"method":"get","path":"/api/issues/{id}/activity","summary":"List activity for an issue","tags":["activity"]},
  {"method":"get","path":"/api/issues/{id}/runs","summary":"List runs for an issue","tags":["activity"]},
  {"method":"get","path":"/api/heartbeat-runs/{runId}/issues","summary":"List issues for a heartbeat run","tags":["activity"]},
  {"method":"get","path":"/api/companies/{companyId}/dashboard","summary":"Get dashboard data","tags":["dashboard"]},
  {"method":"get","path":"/api/companies/{companyId}/sidebar-badges","summary":"Get sidebar badge counts","tags":["sidebar"]},
  {"method":"get","path":"/api/sidebar-preferences/me","summary":"Get current user sidebar preferences","tags":["sidebar"]},
  {"method":"put","path":"/api/sidebar-preferences/me","summary":"Update current user sidebar preferences","tags":["sidebar"]},
  {"method":"get","path":"/api/companies/{companyId}/sidebar-preferences/me","summary":"Get sidebar preferences for company","tags":["sidebar"]},
  {"method":"put","path":"/api/companies/{companyId}/sidebar-preferences/me","summary":"Update sidebar preferences for company","tags":["sidebar"]},
  {"method":"get","path":"/api/companies/{companyId}/inbox-dismissals","summary":"List inbox dismissals","tags":["inbox"]},
  {"method":"post","path":"/api/companies/{companyId}/inbox-dismissals","summary":"Create an inbox dismissal","tags":["inbox"]},
  {"method":"get","path":"/api/instance/settings/general","summary":"Get general instance settings","tags":["instance"]},
  {"method":"patch","path":"/api/instance/settings/general","summary":"Update general instance settings","tags":["instance"]},
  {"method":"get","path":"/api/instance/settings/experimental","summary":"Get experimental instance settings","tags":["instance"]},
  {"method":"patch","path":"/api/instance/settings/experimental","summary":"Update experimental instance settings","tags":["instance"]},
  {"method":"get","path":"/api/companies/{companyId}/invites","summary":"List company invites","tags":["access"]},
  {"method":"post","path":"/api/companies/{companyId}/invites","summary":"Create a company invite","tags":["access"]},
  {"method":"get","path":"/api/companies/{companyId}/join-requests","summary":"List company join requests","tags":["access"]},
  {"method":"post","path":"/api/companies/{companyId}/join-requests/{requestId}/approve","summary":"Approve a company join request","tags":["access"]},
  {"method":"post","path":"/api/companies/{companyId}/join-requests/{requestId}/reject","summary":"Reject a company join request","tags":["access"]},
  {"method":"post","path":"/api/invites/{inviteId}/revoke","summary":"Revoke an invite","tags":["access"]},
  {"method":"get","path":"/api/invites/{token}","summary":"Get an invite by token","tags":["access"]},
  {"method":"post","path":"/api/invites/{token}/accept","summary":"Accept an invite and create or replay a join request","tags":["access"]},
  {"method":"get","path":"/api/companies/{companyId}/members","summary":"List company members","tags":["access"]},
  {"method":"patch","path":"/api/companies/{companyId}/members/{memberId}","summary":"Update a company member status or role","tags":["access"]},
  {"method":"patch","path":"/api/companies/{companyId}/members/{memberId}/role-and-grants","summary":"Update a company member role and explicit grants","tags":["access"]},
  {"method":"post","path":"/api/companies/{companyId}/members/{memberId}/archive","summary":"Archive a company member","tags":["access"]},
  {"method":"patch","path":"/api/companies/{companyId}/members/{memberId}/permissions","summary":"Update explicit company member permissions","tags":["access"]},
  {"method":"get","path":"/api/companies/{companyId}/user-directory","summary":"Get company user directory","tags":["access"]},
  {"method":"get","path":"/api/cli-auth/me","summary":"Get current CLI auth session","tags":["access"]},
  {"method":"post","path":"/api/companies/{companyId}/openclaw/invite-prompt","summary":"Create an OpenClaw invite prompt bundle","tags":["access"]},
  {"method":"post","path":"/api/cli-auth/challenges","summary":"Create a CLI auth challenge","tags":["access"]},
  {"method":"post","path":"/api/cli-auth/challenges/{id}/approve","summary":"Approve a CLI auth challenge","tags":["access"]},
  {"method":"post","path":"/api/cli-auth/challenges/{id}/cancel","summary":"Cancel a CLI auth challenge","tags":["access"]},
  {"method":"post","path":"/api/cli-auth/revoke-current","summary":"Revoke current CLI auth session","tags":["access"]},
  {"method":"get","path":"/api/skills/available","summary":"List available skills","tags":["access"]},
  {"method":"get","path":"/api/skills/index","summary":"Get skills index","tags":["access"]},
  {"method":"get","path":"/api/skills/{skillName}","summary":"Get a skill by name","tags":["access"]},
  {"method":"post","path":"/api/join-requests/{requestId}/claim-api-key","summary":"Claim the initial API key for an approved agent join request","tags":["access"]},
  {"method":"get","path":"/api/admin/users","summary":"List all users (admin)","tags":["admin"]},
  {"method":"get","path":"/api/auth/get-session","summary":"Get current session","tags":["auth"]},
  {"method":"get","path":"/api/auth/profile","summary":"Get current user profile","tags":["auth"]},
  {"method":"patch","path":"/api/auth/profile","summary":"Update current user profile","tags":["auth"]},
  {"method":"get","path":"/api/companies/{companyId}/users/{userSlug}/profile","summary":"Get a user profile within a company","tags":["auth"]},
  {"method":"get","path":"/api/companies/{companyId}/heartbeat-runs","summary":"List heartbeat runs for a company","tags":["runs"]},
  {"method":"get","path":"/api/companies/{companyId}/live-runs","summary":"List live runs for a company","tags":["runs"]},
  {"method":"get","path":"/api/issues/{issueId}/live-runs","summary":"List live runs for an issue","tags":["runs"]},
  {"method":"get","path":"/api/issues/{issueId}/active-run","summary":"Get active run for an issue","tags":["runs"]},
  {"method":"get","path":"/api/heartbeat-runs/{runId}","summary":"Get a heartbeat run","tags":["runs"]},
  {"method":"post","path":"/api/heartbeat-runs/{runId}/cancel","summary":"Cancel a heartbeat run","tags":["runs"]},
  {"method":"post","path":"/api/heartbeat-runs/{runId}/watchdog-decisions","summary":"Submit watchdog decisions for a run","tags":["runs"]},
  {"method":"get","path":"/api/heartbeat-runs/{runId}/events","summary":"Get events for a heartbeat run","tags":["runs"]},
  {"method":"get","path":"/api/heartbeat-runs/{runId}/log","summary":"Get log for a heartbeat run","tags":["runs"]},
  {"method":"get","path":"/api/heartbeat-runs/{runId}/workspace-operations","summary":"List workspace operations for a run","tags":["runs"]},
  {"method":"get","path":"/api/workspace-operations/{operationId}/log","summary":"Get log for a workspace operation","tags":["runs"]},
  {"method":"post","path":"/api/agents/{id}/approve","summary":"Approve a pending agent action","tags":["agents"]},
  {"method":"post","path":"/api/agents/{id}/heartbeat/invoke","summary":"Invoke agent heartbeat","tags":["agents"]},
  {"method":"post","path":"/api/agents/{id}/claude-login","summary":"Trigger Claude login for agent","tags":["agents"]},
  {"method":"get","path":"/api/issues/{id}/interactions","summary":"List issue thread interactions","tags":["issues"]},
  {"method":"post","path":"/api/issues/{id}/interactions","summary":"Create an issue thread interaction","tags":["issues"]},
  {"method":"post","path":"/api/issues/{id}/interactions/{interactionId}/accept","summary":"Accept an issue thread interaction","tags":["issues"]},
  {"method":"post","path":"/api/issues/{id}/interactions/{interactionId}/reject","summary":"Reject an issue thread interaction","tags":["issues"]},
  {"method":"post","path":"/api/issues/{id}/interactions/{interactionId}/respond","summary":"Answer questions on an issue thread interaction","tags":["issues"]},
  {"method":"post","path":"/api/issues/{id}/children","summary":"Create child issues","tags":["issues"]},
  {"method":"post","path":"/api/issues/{id}/admin/force-release","summary":"Force-release an issue (admin)","tags":["issues"]},
  {"method":"get","path":"/api/issues/{id}/tree-control/state","summary":"Get issue tree control state","tags":["issues"]},
  {"method":"post","path":"/api/issues/{id}/tree-control/preview","summary":"Preview issue tree control changes","tags":["issues"]},
  {"method":"get","path":"/api/issues/{id}/tree-holds","summary":"List issue tree holds","tags":["issues"]},
  {"method":"post","path":"/api/issues/{id}/tree-holds","summary":"Create an issue tree hold","tags":["issues"]},
  {"method":"get","path":"/api/issues/{id}/tree-holds/{holdId}","summary":"Get an issue tree hold","tags":["issues"]},
  {"method":"post","path":"/api/issues/{id}/tree-holds/{holdId}/release","summary":"Release an issue tree hold","tags":["issues"]},
  {"method":"post","path":"/api/companies/{companyId}/issues/{issueId}/attachments","summary":"Upload an attachment to an issue","tags":["assets"]},
  {"method":"get","path":"/api/attachments/{attachmentId}/content","summary":"Download attachment content","tags":["assets"]},
  {"method":"delete","path":"/api/attachments/{attachmentId}","summary":"Delete an attachment","tags":["assets"]},
  {"method":"post","path":"/api/companies/{companyId}/assets/images","summary":"Upload an image asset","tags":["assets"]},
  {"method":"post","path":"/api/companies/{companyId}/logo","summary":"Upload company logo","tags":["assets"]},
  {"method":"get","path":"/api/assets/{assetId}/content","summary":"Download asset content","tags":["assets"]},
  {"method":"get","path":"/api/companies/{companyId}/skills","summary":"List skills for a company","tags":["skills"]},
  {"method":"get","path":"/api/companies/{companyId}/skills/{skillId}","summary":"Get a company skill","tags":["skills"]},
  {"method":"get","path":"/api/companies/{companyId}/skills/{skillId}/update-status","summary":"Get skill update status","tags":["skills"]},
  {"method":"get","path":"/api/companies/{companyId}/skills/{skillId}/files","summary":"List skill files","tags":["skills"]},
  {"method":"post","path":"/api/companies/{companyId}/skills","summary":"Create a company skill","tags":["skills"]},
  {"method":"patch","path":"/api/companies/{companyId}/skills/{skillId}/files","summary":"Update a skill file","tags":["skills"]},
  {"method":"post","path":"/api/companies/{companyId}/skills/import","summary":"Import a skill","tags":["skills"]},
  {"method":"post","path":"/api/companies/{companyId}/skills/scan-projects","summary":"Scan project for skills","tags":["skills"]},
  {"method":"post","path":"/api/companies/{companyId}/skills/{skillId}/install-update","summary":"Install a skill update","tags":["skills"]},
  {"method":"delete","path":"/api/companies/{companyId}/skills/{skillId}","summary":"Delete a company skill","tags":["skills"]},
  {"method":"get","path":"/api/companies/{companyId}/execution-workspaces","summary":"List execution workspaces for a company","tags":["execution-workspaces"]},
  {"method":"get","path":"/api/execution-workspaces/{id}","summary":"Get an execution workspace","tags":["execution-workspaces"]},
  {"method":"get","path":"/api/execution-workspaces/{id}/close-readiness","summary":"Check close-readiness of a workspace","tags":["execution-workspaces"]},
  {"method":"get","path":"/api/execution-workspaces/{id}/workspace-operations","summary":"List workspace operations","tags":["execution-workspaces"]},
  {"method":"patch","path":"/api/execution-workspaces/{id}","summary":"Update an execution workspace","tags":["execution-workspaces"]},
  {"method":"post","path":"/api/execution-workspaces/{id}/runtime-services/{action}","summary":"Control a runtime service in a workspace","tags":["execution-workspaces"]},
  {"method":"post","path":"/api/execution-workspaces/{id}/runtime-commands/{action}","summary":"Run a runtime command in a workspace","tags":["execution-workspaces"]},
  {"method":"get","path":"/api/companies/{companyId}/environments","summary":"List environments for a company","tags":["environments"]},
  {"method":"get","path":"/api/companies/{companyId}/environments/capabilities","summary":"Get environment capabilities","tags":["environments"]},
  {"method":"post","path":"/api/companies/{companyId}/environments","summary":"Create an environment","tags":["environments"]},
  {"method":"get","path":"/api/environments/{id}","summary":"Get an environment","tags":["environments"]},
  {"method":"get","path":"/api/environments/{id}/leases","summary":"List leases for an environment","tags":["environments"]},
  {"method":"get","path":"/api/environment-leases/{leaseId}","summary":"Get an environment lease","tags":["environments"]},
  {"method":"patch","path":"/api/environments/{id}","summary":"Update an environment","tags":["environments"]},
  {"method":"delete","path":"/api/environments/{id}","summary":"Delete an environment","tags":["environments"]},
  {"method":"post","path":"/api/environments/{id}/probe","summary":"Probe an environment","tags":["environments"]},
  {"method":"post","path":"/api/companies/{companyId}/environments/probe-config","summary":"Probe environment config","tags":["environments"]},
  {"method":"get","path":"/api/adapters","summary":"List all adapters","tags":["adapters"]},
  {"method":"post","path":"/api/adapters/install","summary":"Install an adapter","tags":["adapters"]},
  {"method":"patch","path":"/api/adapters/{type}","summary":"Enable or disable an adapter","tags":["adapters"]},
  {"method":"patch","path":"/api/adapters/{type}/override","summary":"Pause or resume an adapter's override of a builtin","tags":["adapters"]},
  {"method":"delete","path":"/api/adapters/{type}","summary":"Delete an adapter","tags":["adapters"]},
  {"method":"post","path":"/api/adapters/{type}/reload","summary":"Reload an adapter","tags":["adapters"]},
  {"method":"post","path":"/api/adapters/{type}/reinstall","summary":"Reinstall an adapter","tags":["adapters"]},
  {"method":"get","path":"/api/adapters/{type}/config-schema","summary":"Get adapter config schema","tags":["adapters"]},
  {"method":"get","path":"/api/plugins","summary":"List installed plugins","tags":["plugins"]},
  {"method":"get","path":"/api/plugins/examples","summary":"List example plugins","tags":["plugins"]},
  {"method":"get","path":"/api/plugins/ui-contributions","summary":"List plugin UI contributions","tags":["plugins"]},
  {"method":"get","path":"/api/plugins/tools","summary":"List plugin tools","tags":["plugins"]},
  {"method":"post","path":"/api/plugins/tools/execute","summary":"Execute a plugin tool","tags":["plugins"]},
  {"method":"post","path":"/api/plugins/install","summary":"Install a plugin","tags":["plugins"]},
  {"method":"get","path":"/api/plugins/{pluginId}","summary":"Get a plugin","tags":["plugins"]},
  {"method":"delete","path":"/api/plugins/{pluginId}","summary":"Delete a plugin","tags":["plugins"]},
  {"method":"post","path":"/api/plugins/{pluginId}/enable","summary":"Enable a plugin","tags":["plugins"]},
  {"method":"post","path":"/api/plugins/{pluginId}/disable","summary":"Disable a plugin","tags":["plugins"]},
  {"method":"get","path":"/api/plugins/{pluginId}/health","summary":"Get plugin health","tags":["plugins"]},
  {"method":"get","path":"/api/plugins/{pluginId}/logs","summary":"Get plugin logs","tags":["plugins"]},
  {"method":"post","path":"/api/plugins/{pluginId}/upgrade","summary":"Upgrade a plugin","tags":["plugins"]},
  {"method":"get","path":"/api/plugins/{pluginId}/config","summary":"Get plugin config","tags":["plugins"]},
  {"method":"post","path":"/api/plugins/{pluginId}/config","summary":"Set plugin config","tags":["plugins"]},
  {"method":"post","path":"/api/plugins/{pluginId}/config/test","summary":"Test plugin config","tags":["plugins"]},
  {"method":"get","path":"/api/plugins/{pluginId}/jobs","summary":"List plugin jobs","tags":["plugins"]},
  {"method":"get","path":"/api/plugins/{pluginId}/jobs/{jobId}/runs","summary":"List runs for a plugin job","tags":["plugins"]},
  {"method":"post","path":"/api/plugins/{pluginId}/jobs/{jobId}/trigger","summary":"Trigger a plugin job","tags":["plugins"]},
  {"method":"post","path":"/api/plugins/{pluginId}/webhooks/{endpointKey}","summary":"Deliver an external webhook payload to a plugin","tags":["plugins"]},
  {"method":"get","path":"/api/plugins/{pluginId}/dashboard","summary":"Get plugin dashboard data","tags":["plugins"]},
  {"method":"post","path":"/api/plugins/{pluginId}/bridge/data","summary":"Send data via plugin bridge","tags":["plugins"]},
  {"method":"post","path":"/api/plugins/{pluginId}/bridge/action","summary":"Send action via plugin bridge","tags":["plugins"]},
  {"method":"post","path":"/api/plugins/{pluginId}/data/{key}","summary":"Get plugin data by key (URL-keyed bridge)","tags":["plugins"]},
  {"method":"post","path":"/api/plugins/{pluginId}/actions/{key}","summary":"Invoke a plugin action (URL-keyed bridge)","tags":["plugins"]},
  {"method":"post","path":"/api/instance/database-backups","summary":"Trigger a database backup","tags":["instance"]},
  {"method":"get","path":"/api/llms/agent-configuration.txt","summary":"Get agent configuration as plain text (for LLM context)","tags":["llms"]},
  {"method":"get","path":"/api/llms/agent-configuration/{adapterType}.txt","summary":"Get agent configuration for a specific adapter type","tags":["llms"]},
  {"method":"get","path":"/api/llms/agent-icons.txt","summary":"Get agent icon names as plain text","tags":["llms"]},
  {"method":"get","path":"/api/issues","summary":"Legacy — returns error directing to /api/companies/{companyId}/issues","tags":["issues"]},
  {"method":"get","path":"/api/issues/{id}/comments/{commentId}","summary":"Get a single issue comment","tags":["issues"]},
  {"method":"get","path":"/api/companies/{companyId}/org.svg","summary":"Get org chart as SVG","tags":["companies"]},
  {"method":"get","path":"/api/companies/{companyId}/org.png","summary":"Get org chart as PNG","tags":["companies"]},
  {"method":"get","path":"/api/companies/issues","summary":"Legacy — returns error directing to correct issues path","tags":["companies"]},
  {"method":"post","path":"/api/companies/{companyId}/export","summary":"Export a company (legacy singular form)","tags":["companies"]},
  {"method":"post","path":"/api/companies/import/preview","summary":"Preview a company import (legacy route)","tags":["companies"]},
  {"method":"post","path":"/api/companies/import","summary":"Apply a company import (legacy route)","tags":["companies"]},
  {"method":"get","path":"/api/board-claim/{token}","summary":"Get board claim details by token","tags":["access"]},
  {"method":"post","path":"/api/board-claim/{token}/claim","summary":"Claim a board token","tags":["access"]},
  {"method":"get","path":"/api/cli-auth/challenges/{id}","summary":"Get a CLI auth challenge","tags":["access"]},
  {"method":"get","path":"/api/invites/{token}/logo","summary":"Get company logo for an invite","tags":["access"]},
  {"method":"get","path":"/api/invites/{token}/onboarding","summary":"Get onboarding data for an invite","tags":["access"]},
  {"method":"get","path":"/api/invites/{token}/onboarding.txt","summary":"Get onboarding instructions as plain text","tags":["access"]},
  {"method":"get","path":"/api/invites/{token}/skills/index","summary":"Get skills index for an invite","tags":["access"]},
  {"method":"get","path":"/api/invites/{token}/skills/{skillName}","summary":"Get a skill by name for an invite","tags":["access"]},
  {"method":"get","path":"/api/invites/{token}/test-resolution","summary":"Test invite token resolution","tags":["access"]},
  {"method":"get","path":"/api/admin/users/{userId}/company-access","summary":"Get company access for a user (admin)","tags":["admin"]},
  {"method":"put","path":"/api/admin/users/{userId}/company-access","summary":"Set company access for a user (admin)","tags":["admin"]},
  {"method":"post","path":"/api/admin/users/{userId}/promote-instance-admin","summary":"Promote a user to instance admin","tags":["admin"]},
  {"method":"post","path":"/api/admin/users/{userId}/demote-instance-admin","summary":"Demote a user from instance admin","tags":["admin"]},
  {"method":"post","path":"/api/projects/{id}/workspaces/{workspaceId}/runtime-services/{action}","summary":"Control a runtime service in a project workspace","tags":["projects"]},
  {"method":"post","path":"/api/projects/{id}/workspaces/{workspaceId}/runtime-commands/{action}","summary":"Run a runtime command in a project workspace","tags":["projects"]},
  {"method":"get","path":"/api/plugins/{pluginId}/bridge/stream/{channel}","summary":"Subscribe to a plugin bridge SSE stream","tags":["plugins"]},
  {"method":"get","path":"/api/_plugins/{pluginId}/ui/{filePath}","summary":"Serve plugin UI static file","tags":["plugins"]},
  {"method":"get","path":"/api/adapters/{type}/ui-parser.js","summary":"Get adapter UI parser script","tags":["adapters"]},
];

function toOpenApiPath(path: string): string {
  return path.replace(/:([A-Za-z0-9_]+)/g, "{$1}");
}

export function buildOpenApiDocument() {
  const paths: Record<string, Record<string, unknown>> = {};
  for (const route of OPENAPI_ROUTE_REGISTRATIONS) {
    const openApiPath = toOpenApiPath(route.path);
    paths[openApiPath] ??= {};
    paths[openApiPath][route.method] = {
      tags: route.tags ?? [],
      summary: route.summary ?? `${route.method.toUpperCase()} ${openApiPath}`,
      responses: {
        "200": { description: "OK" },
        "400": { description: "Bad request" },
        "401": { description: "Unauthorized" },
        "403": { description: "Forbidden" },
        "404": { description: "Not found" },
        "500": { description: "Internal server error" },
      },
    };
  }

  return {
    openapi: "3.0.0",
    info: {
      title: "Paperclip API",
      version: "1.0.0",
      description: "REST API for the Paperclip AI agent management platform",
    },
    servers: [{ url: "/" }],
    paths,
  };
}

export function openApiRoutes() {
  const router = Router();
  router.get("/openapi.json", (_req, res) => {
    res.json(buildOpenApiDocument());
  });
  return router;
}
